# Copyright (c) 2018-2020, NVIDIA CORPORATION.

{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') + environ.get('VERSION_SUFFIX', '') %}
{% set minor_version =  version.split('.')[0] + '.' + version.split('.')[1] %}
{% set py_version=environ.get('CONDA_PY', 36) %}
{% set cuda_version='.'.join(environ.get('CUDA', '10.1').split('.')[:2]) %}

package:
  name: cuxfilter
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: py{{ py_version }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - VERSION_SUFFIX

requirements:
  build:
    - {{ compiler('c') }}
    - sysroot_linux-64 {{ sysroot_version }}  # [linux64]
    - sysroot_linux-aarch64 {{ sysroot_version }}  # [aarch64]
  host:
    - python
    - setuptools
  run:
    - python
    - cudf {{ minor_version }}
    - cuspatial {{ minor_version }}
    - dask-cudf {{ minor_version }}
    - dask-cuda {{ minor_version }}
    - datashader>0.13, <0.14
    - holoviews>1.14.1, <=1.14.6
    - numba >=0.54
    - cupy >=7.8.0,<10.0.0a0
    - panel >=0.12.7,<0.13
    - pyppeteer>=0.2.6
    - bokeh>=2.4.2,<=2.5
    - pyproj >=2.4, <=3.1
    - geopandas >=0.9.0,<0.10.0a0
    - nodejs >=12,<15
    - libwebp
    - jupyter-server-proxy
    - pydeck >=0.3, <=0.5.0
    - packaging

test:                                   # [linux64]
  requires:                             # [linux64]
    - cudatoolkit {{ cuda_version }}.*  # [linux64]
  imports:                              # [linux64]
    - cuxfilter                         # [linux64]

about:
  home: http://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GPU accelerated cross filtering with cuDF
