# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ['RAPIDS_PACKAGE_VERSION'].lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cuxfilter
  version: {{ version }}

source:
  path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
    - rapids-build-backend >=0.3.0,<0.4.0.dev0
    - setuptools
    - cuda-version ={{ cuda_version }}
  run:
    # https://github.com/rapidsai/cuxfilter/pull/670
    - bokeh >=3.1,<=3.6.3
    - cudf ={{ minor_version }}
    - cupy >=12.0.0
    - cuspatial ={{ minor_version }}
    - dask-cudf ={{ minor_version }}
    - datashader >=0.15
    - geopandas >=0.11.0
    # Shapely upper-pin is for breaking changes in 2.1.0 not handled by geopandas
    - shapely <2.1.0
    - holoviews>=1.16
    - jupyter-server-proxy
    - libwebp-base
    # Breaking ABI in libxml2==2.14 which gets pulled in as a transitive dependency
    - libxml2 <2.14
    - nodejs >=14
    - numba >=0.59.1,<0.61.0a0
    - numpy >=1.23,<3.0a0
    - packaging
    - panel >=1.0
    - python
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

test:
  requires:
    - cuda-version ={{ cuda_version }}
  imports:
    - cuxfilter

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GPU accelerated cross filtering with cuDF
