# Copyright (c) 2018-2023, NVIDIA CORPORATION.

{% set version = environ.get('RAPIDS_PACKAGE_VERSION', '0.0.0.dev').strip('"').lstrip('v') %}
{% set minor_version = version.split('.')[0] + '.' + version.split('.')[1] %}
{% set cuda_version = '.'.join(environ['RAPIDS_CUDA_VERSION'].split('.')[:2]) %}
{% set cuda_major = cuda_version.split('.')[0] %}
{% set py_version = environ['CONDA_PY'] %}
{% set date_string = environ['RAPIDS_DATE_STRING'] %}

package:
  name: cuxfilter
  version: {{ version }}

source:
  git_url: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: cuda{{ cuda_major }}_py{{ py_version }}_{{ date_string }}_{{ GIT_DESCRIBE_HASH }}_{{ GIT_DESCRIBE_NUMBER }}

requirements:
  host:
    - python
    - setuptools
    - cuda-version ={{ cuda_version }}
  run:
    - bokeh >=3.1
    - cudf ={{ minor_version }}
    - cupy >=12.0.0
    - cuspatial ={{ minor_version }}
    - dask-cudf ={{ minor_version }}
    - datashader >=0.15
    - geopandas >=0.11.0
    - holoviews>=1.16
    - jupyter-server-proxy
    - libwebp
    - nodejs >=14
    - numba >=0.57
    - numpy >=1.21
    - packaging
    - panel >=1.0
    - pyppeteer >=0.2.6
    - python
    - {{ pin_compatible('cuda-version', max_pin='x', min_pin='x') }}

test:
  requires:
    - cuda-version ={{ cuda_version }}
  imports:
    - cuxfilter

about:
  home: https://rapids.ai/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: GPU accelerated cross filtering with cuDF
