# Copyright (c) 2025, NVIDIA CORPORATION.
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  py_version: ${{ env.get("RAPIDS_PY_VERSION") }}
  py_buildstring: ${{ py_version | version_to_buildstring }}
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cuxfilter
  version: ${{ version }}

source:
  path: ../../..

build:
  string: cuda${{ cuda_major }}_py${{ py_buildstring }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cuxfilter

requirements:
  host:
    - cuda-version =${{ cuda_version }}
    - python =${{ py_version }}
    - rapids-build-backend >=0.4.0,<0.5.0.dev0
    - setuptools
    - pip
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - cudf =${{ minor_version }}
    - cupy >=12.0.0
    - dask-cudf =${{ minor_version }}
    - datashader >=0.15
    - geopandas >=0.11.0
    - holoviews>=1.16
    - jupyter-server-proxy
    - libwebp-base
    - nodejs >=14
    - numba >=0.59.1,<0.62.0a0
    - numpy >=1.23,<3.0a0
    - packaging
    - panel >=1.0
    - python

tests:
  - python:
      imports:
        - cuxfilter
      pip_check: false

about:
  homepage: ${{ load_from_file("python/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/pyproject.toml").project.license.text }}
  summary: ${{ load_from_file("python/pyproject.toml").project.description }}
