# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0
schema_version: 1

context:
  version: ${{ env.get("RAPIDS_PACKAGE_VERSION") }}
  minor_version: ${{ (version | split("."))[:2] | join(".") }}
  cuda_version: ${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[:2] | join(".") }}
  cuda_major: '${{ (env.get("RAPIDS_CUDA_VERSION") | split("."))[0] }}'
  date_string: '${{ env.get("RAPIDS_DATE_STRING") }}'
  head_rev: '${{ git.head_rev(".")[:8] }}'

package:
  name: cuxfilter
  version: ${{ version }}

source:
  path: ../../..

build:
  noarch: python
  string: cuda${{ cuda_major }}_${{ date_string }}_${{ head_rev }}
  script:
    content: |
      ./build.sh cuxfilter

requirements:
  host:
    - cuda-version =${{ cuda_version }}
    - python >=3.11
    - rapids-build-backend >=0.4.0,<0.5.0
    - setuptools>=77.0.0
    - pip
  run:
    - ${{ pin_compatible("cuda-version", upper_bound="x", lower_bound="x") }}
    - certifi >=2026.1.4
    - cudf =${{ minor_version }}
    - cupy >=13.6.0
    - dask-cudf =${{ minor_version }}
    - datashader >=0.15
    - geopandas >=0.11.0
    - holoviews>=1.16
    - jupyter-server-proxy
    - libwebp-base
    - nodejs >=14
    - numba >=0.60.0,<0.62.0
    - numba-cuda >=0.22.1
    - numpy >=1.23,<3.0
    - packaging
    - panel >=1.0
    - python
    - requests
    # The two dependencies below ensure this package can only be installed on
    # Linux and set a lower bound for `glibc`
    - __linux
    - __glibc >=2.28

tests:
  - python:
      imports:
        - cuxfilter
      pip_check: false

about:
  homepage: ${{ load_from_file("python/pyproject.toml").project.urls.Homepage }}
  license: ${{ load_from_file("python/pyproject.toml").project.license }}
  summary: ${{ load_from_file("python/pyproject.toml").project.description }}
