name: build

on:
  push:
    branches:
      - "branch-*"
    tags:
      - v[0-9][0-9].[0-9][0-9].[0-9][0-9]
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      date:
        required: true
        type: string
      sha:
        required: true
        type: string
      build_type:
        type: string
        default: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  python-build:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@branch-24.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
  upload-conda:
    needs: [python-build]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-upload-packages.yaml@branch-24.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      date: ${{ inputs.date }}
      sha: ${{ inputs.sha }}
  docs-build:
    if: github.ref_type == 'branch'
    needs: python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.06
    with:
      arch: "amd64"
      branch: ${{ inputs.branch }}
      build_type: ${{ inputs.build_type || 'branch' }}
      container_image: "rapidsai/ci-conda:latest"
      date: ${{ inputs.date }}
      node_type: "gpu-v100-latest-1"
      run_script: "ci/build_docs.sh"
      sha: ${{ inputs.sha }}
  wheel-build:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}
      script: ci/build_wheel.sh
      # This selects "ARCH=amd64 + the latest supported Python + One each of (CUDA 11.x, CUDA 12.x)".
      matrix_filter: '[.[] | select(.ARCH == "amd64")] | group_by(.CUDA_VER | split(".")[0]) | map(max_by([.PY_VER, .CUDA_VER]))'
  wheel-publish:
    needs: wheel-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-publish.yaml@branch-24.06
    with:
      build_type: ${{ inputs.build_type || 'branch' }}
      branch: ${{ inputs.branch }}
      sha: ${{ inputs.sha }}
      date: ${{ inputs.date }}
      package-name: cuxfilter
